apiVersion: v1
kind: Secret
metadata:
  name: calculator-secret
  labels:
    app: calculator
data:
  SERVICEBUS_TOPIC_CONNECTIONSTRING: RW5kcG9pbnQ9c2I6Ly9henNibnMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1jYWxjY29tbTtTaGFyZWRBY2Nlc3NLZXk9VTVGaUNmUGp0YjZLOUh3OHgxamM5eEgvTTFodXRaTTE0K0FTYklucUgzaz07RW50aXR5UGF0aD1henNiY2FsY3RvcGlj
  
  